<?xml version="1.0" ?>
<robot name="factory_cam" xmlns:xacro="http://www.ros.org/wiki/xacro" >
<xacro:include filename = "$(find cam_pack)/urdf/factory_fisheye_cam.plugins.xacro"/>


<xacro:property name="height_off_ground" value="10" />
<xacro:property name="height_off_ground_offset" value="0.2" />
<xacro:property name="cam_separation" value="10" />
<xacro:property name="cam_box_size" value="0.07" />
<xacro:property name="cam_mass" value="0.25" />
<xacro:property name="cam_z_joint_height" value="${height_off_ground - height_off_ground_offset}" />

<xacro:property name="cam_inertia_xx" value="0.00020416666666666668" />
<xacro:property name="cam_inertia_yy" value="0.00020416666666666668" />
<xacro:property name="cam_inertia_zz" value="0.00020416666666666668" />

<xacro:property name="ceiling_mass" value="50" />
<xacro:property name="ceiling_inertia_xx" value="150.16666666666669" />
<xacro:property name="ceiling_inertia_yy" value="337.66666666666674" />
<xacro:property name="ceiling_inertia_zz" value="487.50000000000006" />
<xacro:property name="ceiling_width" value="30" />
<xacro:property name="ceiling_length" value="50" />
<xacro:property name="ceiling_thickness" value="0.5" />


    <!-- Specify material colors here -->
    <material name="blue">
        <color rgba="0 0 0.8 0.8"/>
    </material>
    <material name="red">
        <color rgba="0.8 0 0 1"/>
    </material>
    <material name="grey">
        <color rgba="0.75 0.75 0.75 1"/>
    </material>

    <!-- Gazebo plugin initialization -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/factory_cam</robotNamespace> This robot name is the same as robot name at the top
        </plugin>
    </gazebo>


     <!-- ////////////////////////// === BASE LINK ==== //////////////////////////////////// -->


   <!-- Main base link -->
    <link name="base_link">
        <visual>
        <origin xyz="0 0 ${height_off_ground}" rpy="0 0 0"/>  created at 31 meters above just to have space to work with
        <geometry>
            <box size="${ceiling_width} ${ceiling_length} ${ceiling_thickness}"/>
        </geometry>
        <material name = "blue"/>
        </visual>

        <collision>
            <origin xyz="0 0 ${height_off_ground}" rpy="0 0 0"/>
            <geometry>
                <box size="${ceiling_width} ${ceiling_length} ${ceiling_thickness}"/>
            </geometry>
        </collision>
        <inertial>
        <mass value="${ceiling_mass}" /> This camera was estimated from the mass(weight) of a logitech camera = 0.25kg
        <origin xyz="0 0 ${height_off_ground}" rpy="0 0 0"/> Inertia was calculated from the inertial calculator program
        <inertia ixx="${ceiling_inertia_xx}" ixy="0" ixz="0" iyy="${ceiling_inertia_yy}" iyz="0" izz="${ceiling_inertia_zz}" />
        </inertial>
    </link>
     
    This is for color and physical properties in Gazebo, color won't work with the material tag in gazebo
    only for URDF coloring
    <gazebo reference="base_link">
        <gravity>false</gravity>
        <turnGravityOff>true</turnGravityOff>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/DarkGrey</material>
        <static>true</static>
    </gazebo>

<!-- <link name="link2">-->
<!--        <visual>-->
<!--        <origin xyz="0 0 0" rpy="0 0 0"/>  created at 31 meters above just to have space to work with-->
<!--        <geometry>-->
<!--            <box size="0.5 0.5 0.1"/>-->
<!--        </geometry>-->
<!--        <material name = "blue"/>-->
<!--        </visual>-->
<!--    </link>-->
<!--     -->
<!--    <gazebo reference="link2">-->
<!--        <material>Gazebo/Blue</material>-->
<!--        <static>true</static>-->
<!--    </gazebo>-->

<!--      <joint name="join2" type="fixed">-->
<!--        <origin xyz="${1*cam_separation} ${-1*cam_separation} 0" rpy="0 0 0"/> -->
<!--        <parent link="base_link"/>-->
<!--        <child link="link2"/>-->
<!--    </joint>-->


<!-- <link name="link1">
        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>  created at 31 meters above just to have space to work with
        <geometry>
            <box size="0.5 0.5 0.1"/>
        </geometry>
        <material name = "blue"/>
        </visual>
    </link>
     
    <gazebo reference="link1">
        <material>Gazebo/Blue</material>
        <static>true</static>
    </gazebo>

      <joint name="jo1" type="fixed">
        <origin xyz="${1*cam_separation} ${-2*cam_separation} 0" rpy="0 0 0"/> 
        <parent link="base_link"/>
        <child link="link1"/>
    </joint> -->










    <!-- ////////////////////////// === CAMERA LINKS ==== //////////////////////////////////// -->
 Change camera size to make more visible 0.5 0.5 0.5...original = 0.07 0.07 0.07
    <!-- Camera Link 1-->
    <link name="camera_link_1">
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        </collision>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        <material name="red"/>
        </visual>

        <inertial>
        <mass value="${cam_mass}" /> This camera was estimated from the mass(weight) of a logitech camera = 0.25kg
        <origin xyz="0 0 0" rpy="0 0 0"/> Inertia was calculated from the inertial calculator program
        <inertia ixx="${cam_inertia_xx}" ixy="0" ixz="0" iyy="${cam_inertia_yy}" iyz="0" izz="${cam_inertia_zz}" />
        </inertial>
    </link>

    <gazebo reference="camera_link_1">
        <gravity>false</gravity>
        <turnGravityOff>true</turnGravityOff>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/Red</material>
        <static>true</static>
    </gazebo>

    <!-- Camera Link 2-->
    <link name="camera_link_2">
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        </collision>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        <material name="red"/>
        </visual>

        <inertial>
        <mass value="${cam_mass}" /> This camera was estimated from the mass(weight) of a logitech camera = 0.25kg
        <origin xyz="0 0 0" rpy="0 0 0"/> Inertia was calculated from the inertial calculator program
        <inertia ixx="${cam_inertia_xx}" ixy="0" ixz="0" iyy="${cam_inertia_yy}" iyz="0" izz="${cam_inertia_zz}" />
        </inertial>
    </link>

    <gazebo reference="camera_link_2">
        <gravity>false</gravity>
        <turnGravityOff>true</turnGravityOff>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/Red</material>
        <static>true</static>
    </gazebo>



    <!-- Camera Link 3-->
    <link name="camera_link_3">
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        </collision>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        <material name="red"/>
        </visual>

        <inertial>
        <mass value="${cam_mass}" /> This camera was estimated from the mass(weight) of a logitech camera = 0.25kg
        <origin xyz="0 0 0" rpy="0 0 0"/> Inertia was calculated from the inertial calculator program
        <inertia ixx="${cam_inertia_xx}" ixy="0" ixz="0" iyy="${cam_inertia_yy}" iyz="0" izz="${cam_inertia_zz}" />
        </inertial>
    </link>

    <gazebo reference="camera_link_3">
        <gravity>false</gravity>
        <turnGravityOff>true</turnGravityOff>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/Red</material>
        <static>true</static>
    </gazebo>

    <!-- Camera Link 4-->
    <link name="camera_link_4">
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        </collision>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        <material name="red"/>
        </visual>

        <inertial>
        <mass value="${cam_mass}" /> This camera was estimated from the mass(weight) of a logitech camera = 0.25kg
        <origin xyz="0 0 0" rpy="0 0 0"/> Inertia was calculated from the inertial calculator program
        <inertia ixx="${cam_inertia_xx}" ixy="0" ixz="0" iyy="${cam_inertia_yy}" iyz="0" izz="${cam_inertia_zz}" />
        </inertial>
    </link>

    <gazebo reference="camera_link_4">
        <gravity>false</gravity>
        <turnGravityOff>true</turnGravityOff>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/Red</material>
        <static>true</static>
    </gazebo>

    <!-- Camera Link 5-->
    <link name="camera_link_5">
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        </collision>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        <material name="red"/>
        </visual>

        <inertial>
        <mass value="${cam_mass}" /> This camera was estimated from the mass(weight) of a logitech camera = 0.25kg
        <origin xyz="0 0 0" rpy="0 0 0"/> Inertia was calculated from the inertial calculator program
        <inertia ixx="${cam_inertia_xx}" ixy="0" ixz="0" iyy="${cam_inertia_yy}" iyz="0" izz="${cam_inertia_zz}" />
        </inertial>
    </link>

    <gazebo reference="camera_link_5">
        <gravity>false</gravity>
        <turnGravityOff>true</turnGravityOff>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/Red</material>
        <static>true</static>
    </gazebo>

 <!-- Camera Link 6-->
    <link name="camera_link_6">
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        </collision>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        <material name="red"/>
        </visual>

        <inertial>
        <mass value="${cam_mass}" /> This camera was estimated from the mass(weight) of a logitech camera = 0.25kg
        <origin xyz="0 0 0" rpy="0 0 0"/> Inertia was calculated from the inertial calculator program
        <inertia ixx="${cam_inertia_xx}" ixy="0" ixz="0" iyy="${cam_inertia_yy}" iyz="0" izz="${cam_inertia_zz}" />
        </inertial>
    </link>

    <gazebo reference="camera_link_6">
        <gravity>false</gravity>
        <turnGravityOff>true</turnGravityOff>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/Red</material>
        <static>true</static>
    </gazebo>

<!-- Camera Link 7-->
    <link name="camera_link_7">
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        </collision>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        <material name="red"/>
        </visual>

        <inertial>
        <mass value="${cam_mass}" /> This camera was estimated from the mass(weight) of a logitech camera = 0.25kg
        <origin xyz="0 0 0" rpy="0 0 0"/> Inertia was calculated from the inertial calculator program
        <inertia ixx="${cam_inertia_xx}" ixy="0" ixz="0" iyy="${cam_inertia_yy}" iyz="0" izz="${cam_inertia_zz}" />
        </inertial>
    </link>

    <gazebo reference="camera_link_7">
        <gravity>false</gravity>
        <turnGravityOff>true</turnGravityOff>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/Red</material>
        <static>true</static>
    </gazebo>

	
    <!-- Camera Link 8-->
    <link name="camera_link_8">
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        </collision>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        <material name="red"/>
        </visual>

        <inertial>
        <mass value="${cam_mass}" /> This camera was estimated from the mass(weight) of a logitech camera = 0.25kg
        <origin xyz="0 0 0" rpy="0 0 0"/> Inertia was calculated from the inertial calculator program
        <inertia ixx="${cam_inertia_xx}" ixy="0" ixz="0" iyy="${cam_inertia_yy}" iyz="0" izz="${cam_inertia_zz}" />
        </inertial>
    </link>

    <gazebo reference="camera_link_8">
        <gravity>false</gravity>
        <turnGravityOff>true</turnGravityOff>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/Red</material>
        <static>true</static>
    </gazebo>

<!-- Camera Link 9-->
    <link name="camera_link_9">
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        </collision>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        <material name="red"/>
        </visual>

        <inertial>
        <mass value="${cam_mass}" /> This camera was estimated from the mass(weight) of a logitech camera = 0.25kg
        <origin xyz="0 0 0" rpy="0 0 0"/> Inertia was calculated from the inertial calculator program
        <inertia ixx="${cam_inertia_xx}" ixy="0" ixz="0" iyy="${cam_inertia_yy}" iyz="0" izz="${cam_inertia_zz}" />
        </inertial>
    </link>

    <gazebo reference="camera_link_9">
        <gravity>false</gravity>
        <turnGravityOff>true</turnGravityOff>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/Red</material>
        <static>true</static>
    </gazebo>

    <!-- Camera Link 10-->
    <link name="camera_link_10">
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        </collision>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        <material name="red"/>
        </visual>

        <inertial>
        <mass value="${cam_mass}" /> This camera was estimated from the mass(weight) of a logitech camera = 0.25kg
        <origin xyz="0 0 0" rpy="0 0 0"/> Inertia was calculated from the inertial calculator program
        <inertia ixx="${cam_inertia_xx}" ixy="0" ixz="0" iyy="${cam_inertia_yy}" iyz="0" izz="${cam_inertia_zz}" />
        </inertial>
    </link>

    <gazebo reference="camera_link_10">
        <gravity>false</gravity>
        <turnGravityOff>true</turnGravityOff>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/Red</material>
        <static>true</static>
    </gazebo>

    <!-- Camera Link 11-->
    <link name="camera_link_11">
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        </collision>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        <material name="red"/>
        </visual>

        <inertial>
        <mass value="${cam_mass}" /> This camera was estimated from the mass(weight) of a logitech camera = 0.25kg
        <origin xyz="0 0 0" rpy="0 0 0"/> Inertia was calculated from the inertial calculator program
        <inertia ixx="${cam_inertia_xx}" ixy="0" ixz="0" iyy="${cam_inertia_yy}" iyz="0" izz="${cam_inertia_zz}" />
        </inertial>
    </link>

    <gazebo reference="camera_link_11">
        <gravity>false</gravity>
        <turnGravityOff>true</turnGravityOff>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/Red</material>
        <static>true</static>
    </gazebo>

    <!-- Camera Link 12-->
    <link name="camera_link_12">
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        </collision>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        <material name="red"/>
        </visual>

        <inertial>
        <mass value="${cam_mass}" /> This camera was estimated from the mass(weight) of a logitech camera = 0.25kg
        <origin xyz="0 0 0" rpy="0 0 0"/> Inertia was calculated from the inertial calculator program
        <inertia ixx="${cam_inertia_xx}" ixy="0" ixz="0" iyy="${cam_inertia_yy}" iyz="0" izz="${cam_inertia_zz}" />
        </inertial>
    </link>

    <gazebo reference="camera_link_12">
        <gravity>false</gravity>
        <turnGravityOff>true</turnGravityOff>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/Red</material>
        <static>true</static>
    </gazebo>

    <!-- Camera Link 13-->
    <link name="camera_link_13">
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        </collision>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        <material name="red"/>
        </visual>

        <inertial>
        <mass value="${cam_mass}" /> This camera was estimated from the mass(weight) of a logitech camera = 0.25kg
        <origin xyz="0 0 0" rpy="0 0 0"/> Inertia was calculated from the inertial calculator program
        <inertia ixx="${cam_inertia_xx}" ixy="0" ixz="0" iyy="${cam_inertia_yy}" iyz="0" izz="${cam_inertia_zz}" />
        </inertial>
    </link>

    <gazebo reference="camera_link_13">
        <gravity>false</gravity>
        <turnGravityOff>true</turnGravityOff>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/Red</material>
        <static>true</static>
    </gazebo>
    <!-- Camera Link 14-->
    <link name="camera_link_14">
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        </collision>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        <material name="red"/>
        </visual>

        <inertial>
        <mass value="${cam_mass}" /> This camera was estimated from the mass(weight) of a logitech camera = 0.25kg
        <origin xyz="0 0 0" rpy="0 0 0"/> Inertia was calculated from the inertial calculator program
        <inertia ixx="${cam_inertia_xx}" ixy="0" ixz="0" iyy="${cam_inertia_yy}" iyz="0" izz="${cam_inertia_zz}" />
        </inertial>
    </link>

    <gazebo reference="camera_link_14">
        <gravity>false</gravity>
        <turnGravityOff>true</turnGravityOff>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/Red</material>
        <static>true</static>
    </gazebo>

    <!-- Camera Link 15-->
    <link name="camera_link_15">
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        </collision>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${cam_box_size} ${cam_box_size} ${cam_box_size}"/>
        </geometry>
        <material name="red"/>
        </visual>

        <inertial>
        <mass value="${cam_mass}" /> This camera was estimated from the mass(weight) of a logitech camera = 0.25kg
        <origin xyz="0 0 0" rpy="0 0 0"/> Inertia was calculated from the inertial calculator program
        <inertia ixx="${cam_inertia_xx}" ixy="0" ixz="0" iyy="${cam_inertia_yy}" iyz="0" izz="${cam_inertia_zz}" />
        </inertial>
    </link>

    <gazebo reference="camera_link_15">
        <gravity>false</gravity>
        <turnGravityOff>true</turnGravityOff>
        <mu1>10.0</mu1>
        <mu2>10.0</mu2>
        <material>Gazebo/Red</material>
        <static>true</static>
    </gazebo>







    <!-- ////////////////////////// === Joints ==== //////////////////////////////////// -->
  I can spawn all the camera links at origin 0 0 0  but I use the joints to move them to the positions I want them in.

    <!-- joint = base_link to camera_link -->      camera 1,-2 
    <joint name="camera_joint_1" type="fixed">
        <origin xyz="${1*cam_separation} ${-2*cam_separation} ${cam_z_joint_height}" rpy="0 0 0"/> 
        <parent link="base_link"/>
        <child link="camera_link_1"/>
    </joint>
    1 meter spacing between cameras(not exactly)
    <!-- joint = base_link to camera_link -->       camera 1,-1
    <joint name="camera_joint_2" type="fixed">
        <origin xyz="${1*cam_separation} ${-1*cam_separation} ${cam_z_joint_height}" rpy="0 0 0"/> 
        <parent link="base_link"/>
        <child link="camera_link_2"/>
    </joint>

    <!-- joint = base_link to camera_link -->       camera 1,0
    <joint name="camera_joint_3" type="fixed">
        <origin xyz="${1*cam_separation} ${0*cam_separation}  ${cam_z_joint_height}" rpy="0 0 0"/> 
        <parent link="base_link"/>
        <child link="camera_link_3"/>
    </joint>

     <!-- joint = base_link to camera_link -->       camera 1,1
    <joint name="camera_joint_4" type="fixed">
        <origin xyz="${1*cam_separation} ${1*cam_separation}  ${cam_z_joint_height}" rpy="0 0 0"/> 
        <parent link="base_link"/>
        <child link="camera_link_4"/>
    </joint>

    <!-- joint = base_link to camera_link -->       camera 1,2
    <joint name="camera_joint_5" type="fixed">
        <origin xyz="${1*cam_separation} ${2*cam_separation}  ${cam_z_joint_height}" rpy="0 0 0"/> 
        <parent link="base_link"/>
        <child link="camera_link_5"/>
    </joint>

    <!-- joint = base_link to camera_link -->       camera 0,-2
    <joint name="camera_joint_6" type="fixed">
        <origin xyz="${0*cam_separation} ${-2*cam_separation}  ${cam_z_joint_height}" rpy="0 0 0"/> 
        <parent link="base_link"/>
        <child link="camera_link_6"/>
    </joint>

    <!-- joint = base_link to camera_link -->       camera 0,-1
    <joint name="camera_joint_7" type="fixed">
        <origin xyz="${0*cam_separation} ${-1*cam_separation}  ${cam_z_joint_height}" rpy="0 0 0"/> 
        <parent link="base_link"/>
        <child link="camera_link_7"/>
    </joint>

    <!-- joint = base_link to camera_link -->       camera 0,0 (Center Camera)
    <joint name="camera_joint_8" type="fixed">
        <origin xyz="${0*cam_separation} ${0*cam_separation} ${cam_z_joint_height}" rpy="0 0 0"/> 
        <parent link="base_link"/>
        <child link="camera_link_8"/>
    </joint>

    <!-- joint = base_link to camera_link -->       camera 0,1
    <joint name="camera_joint_9" type="fixed">
        <origin xyz="${0*cam_separation} ${1*cam_separation} ${cam_z_joint_height}" rpy="0 0 0"/> 
        <parent link="base_link"/>
        <child link="camera_link_9"/>
    </joint>

    <!-- joint = base_link to camera_link -->       camera 0,2
    <joint name="camera_joint_10" type="fixed">
        <origin xyz="${0*cam_separation} ${2*cam_separation} ${cam_z_joint_height}" rpy="0 0 0"/> 
        <parent link="base_link"/>
        <child link="camera_link_10"/>
    </joint>

    <!-- joint = base_link to camera_link -->       camera -1,-2
    <joint name="camera_joint_11" type="fixed">
        <origin xyz="${-1*cam_separation} ${-2*cam_separation} ${cam_z_joint_height}" rpy="0 0 0"/> 
        <parent link="base_link"/>
        <child link="camera_link_11"/>
    </joint>

     <!-- joint = base_link to camera_link -->       camera -1,-1
    <joint name="camera_joint_12" type="fixed">
        <origin xyz="${-1*cam_separation} ${-1*cam_separation} ${cam_z_joint_height}" rpy="0 0 0"/> 
        <parent link="base_link"/>
        <child link="camera_link_12"/>
    </joint>

     <!-- joint = base_link to camera_link -->       camera -1,0
    <joint name="camera_joint_13" type="fixed">
        <origin xyz="${-1*cam_separation} ${0*cam_separation} ${cam_z_joint_height}" rpy="0 0 0"/> 
        <parent link="base_link"/>
        <child link="camera_link_13"/>
    </joint>

     <!-- joint = base_link to camera_link -->       camera -1,1
    <joint name="camera_joint_14" type="fixed">
        <origin xyz="${-1*cam_separation} ${1*cam_separation} ${cam_z_joint_height}" rpy="0 0 0"/> 
        <parent link="base_link"/>
        <child link="camera_link_14"/>
    </joint>

     <!-- joint = base_link to camera_link -->       camera -1,2
    <joint name="camera_joint_15" type="fixed">
        <origin xyz="${-1*cam_separation} ${2*cam_separation} ${cam_z_joint_height}" rpy="0 0 0"/> 
        <parent link="base_link"/>
        <child link="camera_link_15"/>
    </joint>
</robot>